### ISSUE TITLE
Checklist para 13/04

### ISSUE THREAD

**Issue by nkgushiken** [nkgushiken/lemniscata#3]
- [x] 1) Criar o repositório principal de voces
- [x] 2) Add todas do grupo no memso repositório
  - [x] 2.1) Extra: Criar o kamban com as atividades
- [x] 3) Versionar os scripts de automação
