### ISSUE TITLE
Checklist para 17/04

### ISSUE THREAD

**Issue by nkgushiken** [nkgushiken/lemniscata#4]
- [x] 1) O ambiente rodando na AWS (devops-pi)
  - [x] 1.1) 1 máquina com o jenkins
  - [x] 1.2) Ambiente para deploy da aplicação [digitalhouse-devops-app](https://github.com/bgsouza/digitalhouse-devops-app)
    - **Proposta 1:**
       - *2 máquinas ec2 free-tier:* 1 para homologação e 1 para produção
    - **Proposta 2:**
       - *1 máquina ec2 free-tier:* que rode o digitalhouse-devops-app send:
         - porta 3000: homologação
         - porta 80: produção

Loop no Ansible: https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html

**Comment by nkgushiken** [comment]
Tasks completos!

**Comment by nkgushiken** [comment]
Ainda está faltando a etapa do Jenkins
