### ISSUE TITLE
Checklist para 20/04

### ISSUE THREAD

**Issue by nkgushiken** [nkgushiken/lemniscata#9]
- [x] **S3** *Pode fazer por playbook*
  - [x] **Criar 2 buckets no s3**
    - [x] digitalhouse_{nome_do_seu_grupo}_homolog
    - [x]  digitalhouse_{nome_do_seu_grupo}_producao
  - [x] **Criar ACL’s específicos para cada bucket**
    - [x] user_homolog => digitalhouse_{nome_do_seu_grupo}_homolog
    - [x] user_producao => digitalhouse_{nome_do_seu_grupo}_producao
  - [x] **Obter os tokens de acesso (Aula 2 de AWS - S3)**

- [x] **Deploys simples**
  - [x] Pipeline simples para deploys em Homolog ou Producao  com os apps: [Node App01](https://github.com/bgsouza/app_node1) ou [Node App02](https://github.com/bgsouza/app_node1)
